// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package routes

import (
	"github.com/google/wire"
	"go-boilerplate/internal/app/controllers"
	"net/http"
)

// Injectors from wire.go:

func InitRoute() http.Handler {
	authController := controllers.CreateAuthController()
	userController := controllers.CreateUserController()
	router := &Router{
		Auth: authController,
		User: userController,
	}
	handler := NewRoute(router)
	return handler
}

// wire.go:

var (
	RouterSet = wire.NewSet(wire.Struct(new(Router), "*"), wire.Bind(new(IRouter), new(*Router)))
	RouteSet  = wire.NewSet(NewRoute, RouterSet)
)
