FROM golang:alpine as builder

RUN apk update && apk add --no-cache gcc g++ make git

WORKDIR $GOPATH/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN make build

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /go/src/app/release/goapp .
COPY --from=builder /go/src/app/config.yml.example ./config.yml
COPY --from=builder /go/src/app/assets ./assets

ENTRYPOINT ["./goapp"]

CMD ["start"]

EXPOSE 80 443
