version: "3"

networks:
  gonet:
    driver: bridge

services:
  ### App ###
  app:
    build:
      context: ./docker/app
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    tty: true
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    networks:
      - gonet

  ### MySQL ###
  mysql:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - gonet

  ### InfluxDB ###
  influxdb:
    build:
      context: ./docker/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/influxdb:/var/lib/influxdb
    ports:
      - "${INFLUXDB_ADMIN_PORT}:8083"
      - "${INFLUXDB_PORT}:8086"
    networks:
      - gonet

  ### Telegraf ###
  telegraf:
    build:
      context: ./docker/telegraf
    networks:
      - gonet

  ### MQTT Broker ###
  mqtt-broker:
    build:
      context: ./docker/mqtt-broker
    ports:
      - "${MQTT_BROKER_PORT}:8883"
    networks:
      - gonet
