// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package postgres

import (
	"github.com/google/wire"
	"go-boilerplate/internal/auth/entity"
	"go-boilerplate/pkg/database/orm"
)

// Injectors from wire.go:

func InitialUserRepository() entity.UserRepository {
	string2 := _wireStringValue
	db := orm.GetDB(string2)
	entityUserRepository := NewUserRepository(db)
	return entityUserRepository
}

var (
	_wireStringValue = "postgres"
)

// wire.go:

var (
	UserRepositorySet = wire.NewSet(NewUserRepository, orm.GetDB, wire.Value("postgres"))
)
