// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package postgres

import (
	"github.com/google/wire"
	"go-boilerplate/internal/auth/database"
	"go-boilerplate/internal/auth/entity"
)

// Injectors from wire.go:

func InitialUserRepository() entity.UserRepository {
	db := database.GetDB()
	entityUserRepository := NewUserRepository(db)
	return entityUserRepository
}

// wire.go:

var (
	UserRepositorySet = wire.NewSet(NewUserRepository, database.GetDB)
)
