// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"github.com/google/wire"
	"go-boilerplate/internal/auth/service"
)

// Injectors from wire.go:

func InitializeRouter() Router {
	userHandler := InitialUserHandler()
	router := NewRouter(userHandler)
	return router
}

func InitialUserHandler() *UserHandler {
	userService := service.InitialUserService()
	userHandler := NewUserHandler(userService)
	return userHandler
}

// wire.go:

var (
	UserHandlerSet = wire.NewSet(NewUserHandler, service.InitialUserService)
)
