// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package auth

import (
	"github.com/google/wire"
	"go-boilerplate/pkg/user"
)

// Injectors from wire.go:

func CreateController() *Controller {
	db := user.NewDB()
	repository := user.NewRepository(db)
	service := NewService(repository)
	controller := NewController(service)
	return controller
}

func CreateService() *Service {
	db := user.NewDB()
	repository := user.NewRepository(db)
	service := NewService(repository)
	return service
}

// wire.go:

var (
	ServiceSet    = wire.NewSet(NewService, wire.Bind(new(IRepository), new(*user.Repository)), user.RepositorySet)
	ControllerSet = wire.NewSet(NewController, ServiceSet)
)
