// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package auth

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateController CreateController
func CreateController() *Controller {
	db := NewDB()
	repository := NewRepository(db)
	service := NewService(repository)
	controller := NewController(service)
	return controller
}

// CreateService CreateService
func CreateService() *Service {
	db := NewDB()
	repository := NewRepository(db)
	service := NewService(repository)
	return service
}

// wire.go:

var (
	RepositorySet = wire.NewSet(NewRepository, NewDB)
	ServiceSet    = wire.NewSet(NewService, wire.Bind(new(IRepository), new(*Repository)), RepositorySet)
	ControllerSet = wire.NewSet(NewController, ServiceSet)
)
