// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package auth

import (
	"github.com/google/wire"
	"go-boilerplate/pkg/models"
	"go-boilerplate/pkg/user"
)

// Injectors from wire.go:

func InitRoute() Router {
	db := models.GetDB()
	repository := user.NewRepository(db)
	service := NewService(repository)
	controller := NewController(service)
	router := NewRoute(controller)
	return router
}

func CreateService() *Service {
	db := models.GetDB()
	repository := user.NewRepository(db)
	service := NewService(repository)
	return service
}

// wire.go:

var (
	ServiceSet    = wire.NewSet(NewService, wire.Bind(new(IRepository), new(*user.Repository)), user.RepositorySet)
	ControllerSet = wire.NewSet(NewController, ServiceSet)
	RouteSet      = wire.NewSet(NewRoute, ControllerSet)
)
