// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package routes

import (
	"github.com/google/wire"
	"go-boilerplate/pkg/auth"
	"go-boilerplate/pkg/user"
	"net/http"
)

// Injectors from wire.go:

func InitRoute() http.Handler {
	db := user.NewDB()
	repository := user.NewRepository(db)
	service := auth.NewService(repository)
	controller := auth.NewController(service)
	router := &Router{
		Auth: controller,
	}
	handler := NewRoute(router)
	return handler
}

// wire.go:

var (
	RouterSet = wire.NewSet(wire.Struct(new(Router), "*"), wire.Bind(new(IRouter), new(*Router)))
	RouteSet  = wire.NewSet(NewRoute, RouterSet)
)
