// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"github.com/google/wire"
	"go-boilerplate/internal/app/services"
)

// Injectors from wire.go:

func CreateAuthController() *AuthController {
	authService := services.CreateAuthService()
	authController := NewAuthController(authService)
	return authController
}

func CreateUserController() *UserController {
	userService := services.CreateUserService()
	userController := NewUserController(userService)
	return userController
}

// wire.go:

var (
	authControllerSet = wire.NewSet(NewAuthController, services.CreateAuthService)
	userControllerSet = wire.NewSet(NewUserController, services.CreateUserService)
)
