// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"github.com/google/wire"
	"go-boilerplate/pkg/models"
)

// Injectors from wire.go:

func CreateRepository() *Repository {
	db := models.GetDB()
	repository := NewRepository(db)
	return repository
}

// wire.go:

var (
	RepositorySet = wire.NewSet(NewRepository, models.GetDB)
)
